version: "3"
services:
  postgres_bitcoin_api:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      bitcoin_api_db:
        ipv4_address: ${DB_HOST}

  pgadmin_bitcoin_api:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "email@email.com"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - postgres_bitcoin_api
    networks:
      bitcoin_api_db:
        ipv4_address: 172.19.0.13
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
      - ./pgpass:/pgpass

  redis_bitcoin_api:
    image: redis:latest
    networks:
      bitcoin_api_db:
        ipv4_address: ${REDIS_HOST}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: always

networks:
  bitcoin_api_db:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1